### PR TITLE
sns: Handle all SNS API errors

### LINKED ISSUE #260: Misleading reason for the "Subscribed" status condition
The following status condition is set on my AWSSNSSource:

```yaml
- lastTransitionTime: "2021-01-26T12:12:10Z"
  message: The receive adapter did not report its public URL yet
  reason: MissingAdapterURL
  status: "False"
  type: Subscribed
```

However, the receive adapter is deployed and does report its URL:

```console
$ kubectl get services.serving.knative.dev
NAME                  URL                                              LATESTCREATED               LATESTREADY                 READY   REASON
awssnssource-sample   http://awssnssource-sample.default.example.com   awssnssource-sample-00002   awssnssource-sample-00002   True
```

By looking at the Kubernetes events generated by the controller, it appears that the reconciliation failed due to some authentication issue, bypassing the condition update:

```
  Warning  InternalError    6m    awssnssource-controller  finding subscription: listing subscriptions for topic: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
           status code: 403, request id: 70d4b834-ffaf-5002-b8a5-e0bef0a0178c
```

When a generic AWS error such as the one above occurs, I would expect the reason for the `Subscribed` status condition to be updated accordingly.

Moreover, auth errors should be marked as permanent, so that the reconciler doesn't unnecessarily retry them over and over again.
Another example of error that exhibits the same behaviour is `NotFound: Topic does not exist` (another AWS API error).

---

Edit: This same error also blocks the finalizer.

### PR DESCRIPTION
**Pull request by antoineco**
Fixes #260

A small PR that addresses 3 issues related to error handling.

---

1\. Fixes an issue where some SNS API errors were not properly handled, causing a flood of Kubernetes events and unnecessary retries:

```
Events:
  Type     Reason           Age     From                     Message
  ----     ------           ----    ----                     -------
  Warning  InternalError    26m     awssnssource-controller  finding subscription: listing subscriptions for topic: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
           status code: 403, request id: f063e0aa-fb07-5cd3-8ac9-b8203ae0d906
  Warning  InternalError    26m     awssnssource-controller  finding subscription: listing subscriptions for topic: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
           status code: 403, request id: 42c0fe91-2ca3-5c40-81e4-a61bed4be995
  Warning  InternalError    26m     awssnssource-controller  finding subscription: listing subscriptions for topic: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
           status code: 403, request id: 92314bbf-e817-5f9f-b6ac-133529ffca4a
  Warning  InternalError    26m     awssnssource-controller  finding subscription: listing subscriptions for topic: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
           status code: 403, request id: 07e4d475-0f38-55b6-87d4-8cffced0d063
  Warning  InternalError    5m18s (x16 over 26m)  awssnssource-controller  (combined from similar events): finding subscription: listing subscriptions for topic: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
           status code: 403, request id: 07e858f6-ce03-5acf-8cda-007c08c4cd7d
...
 ```

SNS API errors are now correctly handled, and unretriable errors aren't retried:
 
```
Events:
  Type     Reason           Age     From                     Message
  ----     ------           ----    ----                     -------
  Warning  FailedSubscribe  19s     awssnssource-controller  Error communicating with the SNS API: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. Consult the service documentation for details.
```

---

2\. When an API error prevents the reconciler from listing existing subscriptions, the reason "APIError" is now correctly propagated to the source's status:

```console
$ kubectl get awssnssources.sources.triggermesh.io sample
NAME     READY   REASON     URL                                              SINK                                             AGE
sample   False   APIError   http://awssnssource-sample.default.example.com   http://event-display.default.svc.cluster.local   3h9m
```

```yaml
- lastTransitionTime: "2021-01-27T01:45:22Z"
  message: API call rejected
  reason: APIError
  status: "False"
  type: Subscribed
```

---

3\. All API responses with HTTP code `401` or `403` are now considered as denied and handled accordingly (e.g. release the finalizer if this occurs during finalization), not only the ones returned by SNS with the reason "AuthorizationErrorException".

### CODE REVIEW

File: pkg/reconciler/awssnssource/subscription.go [hunk 1]
```diff
@@ -96,6 +97,13 @@ func (r *Reconciler) ensureSubscribed(ctx context.Context) error {
 
 		event.Normal(ctx, ReasonSubscribed, "Subscribed to SNS topic %q", topicARN)
 
+	case isAWSError(err):
+		// All documented API errors require some user intervention and
+		// are not to be retried.
+		// https://docs.aws.amazon.com/sns/latest/api/API_Subscribe.html#API_Subscribe_Errors
+		status.MarkNotSubscribed(v1alpha1.AWSSNSReasonAPIError, "API call rejected")
+		return controller.NewPermanentError(apiErrorEvent(err))
```
Comment (antoineco) [inline pkg/reconciler/awssnssource/subscription.go:105]: Fixes both 1 and 2.

File: pkg/reconciler/awssnssource/subscription.go [hunk 2]
```diff
@@ -267,6 +275,11 @@ func isNotFound(err error) bool {
 // API could not be authorized.
 func isDenied(err error) bool {
 	if awsErr := awserr.Error(nil); errors.As(err, &awsErr) {
+		if awsReqFail := awserr.RequestFailure(nil); errors.As(err, &awsReqFail) {
+			code := awsReqFail.StatusCode()
+			return code == http.StatusUnauthorized || code == http.StatusForbidden
+		}
+
```
Comment (antoineco) [inline pkg/reconciler/awssnssource/subscription.go:282]: Fixes 3.

**Review by odacremolbap — APPROVED** [review]
